services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
      - "127.0.0.1:49xx:4983"  # Drizzle Studio - replace DBPORT with actual port. NB. also update the port inside db:studio:remote in package.json
    volumes:
      # Mount db directory to persist SQLite data
      - ./db-data:/app/db
    environment:
      - DATABASE_PATH=/app/db/data.db
      - PUBLIC_APP_URL=http://localhost:4321
      - PUBLIC_APP_NAME=App Name
      - NODE_ENV=production
    restart: unless-stopped
